require_relative "lib/helpers"

show_problem_info({
  number: 2,
  title: "Even Fibonacci numbers",
  statement: %Q{
    Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
  },
  url: "https://projecteuler.net/problem=2"
})

LIMIT = 4000000

benchmark_solution(4613732) do
  fib_a, fib_b = 0, 1

  sum = 0
  begin
    sum += fib_b if fib_b.even?
    fib_b, fib_a = fib_b + fib_a, fib_b
  end while fib_b < LIMIT
  sum
end
